# Autogenerated wrapper script for LinearElasticity_jll for armv6l-linux-gnueabihf
export elastic, libCommons, libElas

JLLWrappers.@generate_wrapper_header("LinearElasticity")
JLLWrappers.@declare_library_product(libCommons, "libCommons.so")
JLLWrappers.@declare_library_product(libElas, "libElas.so")
JLLWrappers.@declare_executable_product(elastic)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libCommons,
        "lib/libCommons.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libElas,
        "lib/libElas.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        elastic,
        "bin/elastic",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
