# Autogenerated wrapper script for LinearElasticity_jll for x86_64-w64-mingw32
export elastic, libCommons, libElas

JLLWrappers.@generate_wrapper_header("LinearElasticity")
JLLWrappers.@declare_library_product(libCommons, "libCommons.dll")
JLLWrappers.@declare_library_product(libElas, "libElas.dll")
JLLWrappers.@declare_executable_product(elastic)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libCommons,
        "bin\\libCommons.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libElas,
        "bin\\libElas.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        elastic,
        "bin\\elastic.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
